DROP TABLE ATTRIBUTE_DATA;

CREATE TABLE ATTRIBUTE_DATA
(
   ATTRIBUTE_NAME VARCHAR(50),
   OCURRENCES     INTEGER,
   MAX_IDF        DOUBLE
);

DROP TABLE IDF;

CREATE TABLE IDF
(
   ATTRIBUTE_NAME VARCHAR(50),
   ATTRIBUTE      VARCHAR(500),
   CNT            INTEGER
);

CREATE INDEX IDX_IDF 
    ON IDF (ATTRIBUTE_NAME ASC, ATTRIBUTE ASC);

DROP TABLE IDF_PAIR;

CREATE TABLE IDF_PAIR
(
   ATTRIBUTE_NAME VARCHAR(50),
   ATTRIBUTE1     VARCHAR(500),
   ATTRIBUTE2     VARCHAR(500),
   CNT            INTEGER
);

CREATE INDEX IDX_IDF_PAIR 
    ON IDF_PAIR (ATTRIBUTE_NAME ASC, ATTRIBUTE1 ASC, ATTRIBUTE2 ASC);

DROP TABLE IDF_PAIR_AUX;

CREATE TABLE IDF_PAIR_AUX
(
   ATTRIBUTE_NAME VARCHAR(50),
   OBJ_INDEX      INTEGER,
   ATTRIBUTE      VARCHAR(500)
);

