DROP TABLE DUP_FOUND;

CREATE TABLE DUP_FOUND
(
   NODE1_INDEX INTEGER,
   NODE2_INDEX INTEGER,
   SIMILARITY  DOUBLE,
   DUP         VARCHAR(3)
);

DROP TABLE DBLOAD;

CREATE TABLE DBLOAD
(
   ID		INTEGER,
   ATTRIBUTE	VARCHAR(500),
   CONTENT	TEXT,
   OCURRENCE	INTEGER,
   DATA_TYPE    INTEGER
);

DROP TABLE DISTANCE;

CREATE TABLE DISTANCE
(
   STRING1 	TEXT,
   STRING2      TEXT,
   DISTANCE     DOUBLE
);

DROP TABLE CLUSTERS;

CREATE TABLE CLUSTERS
(
  ATTRIBUTE	TEXT,
  CONTENT	TEXT,		
  DISTANCE	DOUBLE,       
  OCURRENCES	INTEGER,
  CLUSTER	INTEGER
);

DROP TABLE FEATURES_ASSGN;

CREATE TABLE FEATURES_ASSGN
(
  DistinctivenessEntropy DOUBLE,
  AVGStringSize DOUBLE,		
  StringSizeEntropy DOUBLE,
  Emptiness DOUBLE,    
  NonNumericContentRate DOUBLE,
  NumericContentRate DOUBLE,
  MixedContentRate DOUBLE,
  Attribute TEXT,
  DB TEXT,
  NodeLevel INTEGER,
  RelativeDepth FLOAT
);



